### ISSUE TITLE
Add "are you sure you want to leave" popup to freeCodeCamp

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#12]
I have, frequently enough, accidentally hit the backspace or clicked a button, that made me leave a tutorial/CodeAlly container. Basically, making me lose all my progress. A number of websites have a popup in situations like this, that say something like, "are you sure you want to leave" - making users click a button before they can leave. I think this should be added to give one more step before someone can exit a container.

Edit: I noticed that the native CodeAlly experience is fairly smooth, if you leave and want to go back - it starts the container up quite quick. And one specific button, does bring up a pop-up like that. Perhaps, solving https://github.com/moT01/CodeAlly-CodeRoad-freeCodeCamp/issues/11 will give a similar experience. Also, this may be something we can add on the fCC side - not sure.

**Comment by AdamZaczek** [comment]
As discussed, it will be best to handle this on Freecodecamp's end.

**Comment by moT01** [comment]
I am going to close this as stale. With how far we've come with the integration - users can get back to where they were quite quickly. I don't think I've seen any issues around this on the forum and I don't think it's necessary for now.
