### ISSUE TITLE
Startup terminal commands not working in CodeAlly

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#13]
The [startup terminal commands](https://github.com/moT01/.learn-bash-scripting-by-building-five-programs/blob/main/strove.json#L2) don't seem to be working at the moment. I didn't play around with the terminal that shows up when a container loads, it seems a little different/interesting - but, there's a few steps I need to take to close it:

![Mar-30-2021 15-46-00](https://user-images.githubusercontent.com/20648924/113054817-77120880-916f-11eb-8a55-e03ea5a77c05.gif)

This is a significant step that I would need to try and explain to a user. The `exit` command in the link above is to just close the terminal, making users open a new one so the `.bashrc` commands are applied. The `.bashrc` file is added by my CodeRoad tutorial and the commands are for generating logs which I can test against.

Not sure how I think this should be solved. At a minimum, it would nice be if those commands worked. Still leaving the user with a few steps to open a new terminal.

Ideally, I suppose, a tutorial would load with the terminal open and the `.bashrc` applied. I thought I tried a `source ~/.bashrc` command in my tutorial to eliminate a step and it didn't work - need to try it again. That would probably only be for my tutorials - there is going to be many others down the road that don't need a terminal at all. I'm thinking out loud at this point. Any suggestions are welcome.

**Comment by AdamZaczek** [comment]
I'll get this sorted.
There will be 2 changes:
No read-only terminal popping for tutorials
Init command working

**Comment by moT01** [comment]
Thanks @AdamZaczek 🎉 This one looks to be fixed
