### ISSUE TITLE
Auto load CodeRoad on start

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#14]
I know you guys played around with this a little. Not sure if it's even possible, but the best experience would be if CodeRoad loaded automatically when a tutorial is started.

**Comment by AdamZaczek** [comment]
We're want to solve a bunch of CodeAlly + CodeRoad integration issues, including this one all at once. We're waiting for one fix on the code-server side to handle them.

**Comment by AdamZaczek** [comment]
We should be able to use the code-server CLI for this: https://github.com/cdr/code-server/issues/642.
We will experiment with it once we update our Docker image.

**Comment by AdamZaczek** [comment]
It seems we found a way to do this well. We can open Coderoad if the project has a codeally.json file.

**Comment by AdamZaczek** [comment]
This is handled on the coderoad side. Thanks @ShMcK! We'll update the default coderoad version once https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/26 is handled.

@moT01 Coderoad will auto-open any project with codeally.json such as https://github.com/codeallyio/postgres-example/blob/master/codeally.json.

**Comment by AdamZaczek** [comment]
This is handled on the coderoad side. Thanks @ShMcK! We'll update the default coderoad version once https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/26 is handled.

@moT01 Coderoad will auto-open in any project with codeally.json such as https://github.com/codeallyio/postgres-example/blob/master/codeally.json.

**Comment by ShMcK** [comment]
Released in CodeRoad v0.17
