### ISSUE TITLE
Get fCC user info to and from a tutorial (add webhook URL)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#18]
Not sure on this one, but we will want to know if an fCC user has completed a tutorial so we can put it in our DB and know if they did all the projects for a cert, or so we can put a checkmark next to what they've completed, etc... 

@raisedadead mentioned that this shouldn't be a problem at point, can you provide any input here?

**Comment by moT01** [comment]
On the fCC end, we will need to generate URL's for users. On the CodeRoad end, we need a place to enter that URL to submit steps or entire tutorials/projects

**Comment by AdamZaczek** [comment]
This one is should be already handled @moT01. Let me know if there are any issues!

You can pass any environment variables to the docker container like this
```
https://codeally.io/embed/?repoUrl=https://github.com/codeallyio/hackathon-starter-codeally&envVariables=ENV_VARIABLE=VALUE,ANOTHER_VARIABLE=ANOTHER_VALUE
```

**Comment by AdamZaczek** [comment]
You can pass any environment variables to the docker container like this
```
https://codeally.io/embed/?repoUrl=https://github.com/codeallyio/hackathon-starter-codeally&envVariables=ENV_VARIABLE=VALUE,ANOTHER_VARIABLE=ANOTHER_VALUE
```

Let me know if there are any issues!

**Comment by moT01** [comment]
I am having an issue @AdamZaczek - I opened one of my URL's, similar to the example you just gave, to test things - I'm quite sure I didn't include any variables when I opened it - now, every embed link I open takes me to the same container (including the example you gave). I [outlined some more details here](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/11#issuecomment-934756548). I cannot confirm if the envVariables are working since I cannot create a new container. The [dashboard you mentioned](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/24#issuecomment-934805245) would be nice, so I (and anyone) could manually delete containers if one becomes problematic or something.

**Comment by AdamZaczek** [comment]
I see, we're on it!

**Comment by AdamZaczek** [comment]
@moT01 This should work now. Let me know if you see any issues!

**Comment by moT01** [comment]
They don't seem to be working quite right @AdamZaczek

When I use a URL like the one you shared directly in the address bar, they show up when I `printenv` in the terminal of the container

When I have the URL in an `<iframe>`, they don't show up. I tested it a number of times. That seems to be the difference.

**Comment by moT01** [comment]
This appears to be working now - thanks @AdamZaczek 🎉
