### ISSUE TITLE
Boilerplate repo management.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#20]
Boilerplate repos for projects have a name like so: [`.learn-bash-by-building-a-boilerplate`](https://github.com/freeCodeCamp/.learn-bash-by-building-a-boilerplate), we would want to follow the general naming convention for most our boilerplate repos.

We would also additionally want to see if CodeAlly can instead clone a repo and followed by an intermediate "build" step that adds a `.` to hide the repo.

Please add any context, steps details that I might be missing.

**Comment by AdamZaczek** [comment]
This can be handled by the init command once it works correctly. It would not be instant but take +/- 2 seconds on average to have the repo name updated.

**Comment by moT01** [comment]
I think this is safe to close - the repos have been renamed and transferred to fCC org
