### ISSUE TITLE
Hide welcome screen on start up

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#22]
Note to self - add this so vscode settings: "workbench.startupEditor": "none"

**Comment by moT01** [comment]
This actually doesn't seem to work on my end. The settings I have get applied after CodeRoad is loaded and VSCode is already open with the welcome screen up. So the setting gets added, but the welcome screen stays open. I can look into seeing if there's a way to close it after it's already open - I feel like that's unlikely. Or perhaps there's something else I can do - not sure yet.

I thought I remember you saying there might be a way on your end to do this @AdamZaczek - maybe I am misremembering? This is not a priority right now.

**Comment by AdamZaczek** [comment]
We will check. The startup screen should never be shown in general.
