### ISSUE TITLE
Add back preview functionality

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#23]
There used to be a "preview" drop down menu in the blue bar at the top of a CodeAlly VM for viewing locally running ports. It doesn't seem to be there anymore. You can see it in this [screen shot](https://user-images.githubusercontent.com/20648924/113049490-50e96a00-9169-11eb-8afa-0aae2eafc416.png) from another issue (ignore the red square - it's the `preview` at the top left). I'm not sure if it's not there anymore or if it's just not showing up for me. I don't need it for the relational database stuff I'm working on - but for the node, express, and the rest of the backend stuff, we will probably need it. Would it be tough to add that back in for us @AdamZaczek?

**Comment by moT01** [comment]
Let me confer with @scissorsneedfoodtoo, we may not actually need it - probably better to have it, though.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, I think you're right -- for the relational DB projects, and some of the projects for later sections (Learn npm by Building an npm Module), we probably won't need the preview. But for other practice or required projects with front ends we will need the preview back.

**Comment by moT01** [comment]
I found a way around this. The ability to view the page is there, the preview button just isn't. I don't think this is entirely necessary at the moment.

**Comment by AdamZaczek** [comment]
Hey! Sorry for being late for the party! We will bring the preview button back.

**Comment by AdamZaczek** [comment]
This should have been fixed now!

**Comment by moT01** [comment]
This looks good 👍 Thanks @AdamZaczek & CodeAlly team 🎉
