### ISSUE TITLE
Login/auth methods/container type for CodeAlly

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#24]
With the new way to add CodeRoad to containers. I am able to log in to CodeAlly in two different ways and go through tutorials.

1. The first is the default method on CodeAlly. This only works for me if I go to CodeAlly.io and log in there first using the login button at the top.

    - Pros:
      - Terminal Commands run
      - Container loads up automatically

    - Cons:
      - Panel on the right isn't needed - other than maybe the ability to preview running ports. Could possibly just collapse this by default.

2. The second is using the `For Developers (alpha)` button in the footer of CodeAlly. This seems to be the method used when I click on a tutorial and login through the freeCodeCamp website. Not sure if that’s cause it’s me, or if that’s what everyone will get. I did try with a second account and this seemed to be the method used.

    - Pros:
      - The panel on the right isn't there

    - Cons:
      - Terminal commands don't run
      - Container hangs when trying to load

Seems like the best would a mix of the two. I'm sure you are aware of some of this @AdamZaczek and maybe already have a plan - but I made a video to show you exactly what I see. The first half uses the first login method, the second half uses the second method.

https://www.youtube.com/watch?v=qeub722ocL0

Let me know if you want help looking into any of these @AdamZaczek

**Comment by AdamZaczek** [comment]
I will work on a way to combine both methods. I knew the issue is there and I've been preparing to handle it.

Some of the cons of the alpha version of dev login are that it's also not optimized at all. I believe it loads for quite some time on your end.

I'm on it.

**Comment by moT01** [comment]
I think we're safe to close this. Most of the issues are fixed - we can create new ones for more specific issues. Feel free to let me know if you want it to stay open @AdamZaczek

**Comment by AdamZaczek** [comment]
We can close! I will finish a better version of the dashboard but it's not strictly needed.
