### ISSUE TITLE
Unable to install coderoad using open-vsx

### ISSUE THREAD

**Issue by AdamZaczek** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#25]
We have updated our Docker image to the newest vscode!
We are also using open-vsx now. This means we can probably deal with all the missing coderoad issues.
It seems like coderoad still needs to be approved in open-vsx first though.

**Describe the bug**
Coderoad can not be found in open-vsx https://open-vsx.org/?search=coderoad&category=&sortBy=relevance&sortOrder=desc

We should be able to search for it there.

**To Reproduce**
1. Go to https://open-vsx.org/?search=coderoad&category=&sortBy=relevance&sortOrder=desc
2. See missing coderoad

**Expected behavior**
Coderoad can be found in open-vsx.

**Additional context**
This one is probably just a matter of doing a release.

**Comment by moT01** [comment]
> This one is probably just a matter of doing a release.

Meaning, on the next CodeRoad release, you would expect it to show up there?

**Comment by AdamZaczek** [comment]
> > This one is probably just a matter of doing a release.
> 
> Meaning, on the next CodeRoad release, you would expect it to show up there?

Meaning, Shawn can probably fix this, by releasing thecoderoad to open-vsx, similarly to how it has been released to vscodes extension library.

**Comment by ShMcK** [comment]
@AdamZaczek I've just published CodeRoad to open-vsx. Let me know if you have any issues!

https://open-vsx.org/extension/coderoad/coderoad

**Comment by AdamZaczek** [comment]
Thanks! I can install it. I'm closing this one.
