### ISSUE TITLE
Coderoad installs but doesn't finish loading on start

### ISSUE THREAD

**Issue by AdamZaczek** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#26]
**Describe the bug**
Newest coderoad does not start in CodeAlly. I think, it's on our end but I just started looking into it.

**Expected behavior**
Coderoad successfully loads

**Screenshots**
Screenshot with an error that causes the problem:
![image](https://user-images.githubusercontent.com/14284341/128973718-423aeba7-9493-47c4-8211-40db487c38af.png)

**Comment by moT01** [comment]
I just saw this issue, any luck @AdamZaczek? I noticed this problem, sometimes it loads right away - others, I had to close and reopen CodeRoad up to several times before it loaded.

**Comment by AdamZaczek** [comment]
It seems like we need to update docker image to change html to enable fetching script correctly @moT01 
```
main.js:694 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-a9FW4KuQ3xUECwA4k25QR6pjNYmxpa0q' 'nonce-UHoT18lr2uxovhFUbo2us79Bd8l1zbia' 'nonce-ioQJ2SDnQXu8waJOvQ9QDOTvVewC6dD2' data:". Either the 'unsafe-inline' keyword, a hash ('sha256-O6s4HZqHNjMzg0UZUFHy0YEAlG05lWCXf0lBN+GmShk='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by AdamZaczek** [comment]
I did some additional digging by looking at all the iframes. The issue is in Coderoad after all @ShMcK @moT01 .
Appending the hash:
```
sha256-O6s4HZqHNjMzg0UZUFHy0YEAlG05lWCXf0lBN+GmShk=
```
in https://github.com/coderoad/coderoad-vscode/blob/417d9dcf09587f7f3e0755fb9dd2feba9f1fb774/src/services/webview/render.ts should do the job.

**Comment by ShMcK** [comment]
@AdamZaczek do you know what generates that hash? Is it random each time, or consistent?
I'll add any additional CSP exceptions as an env variable and follow up

**Comment by ShMcK** [comment]
🚀  Published coderoad.coderoad v0.14.5 on Open-vsx.

To make it work, include an environmental variable: `CODEROAD_CONTENT_SECURITY_POLICY_EXEMPTIONS` set to the hash.

Let me know if there are any issues.

**Comment by AdamZaczek** [comment]
@ShMcK Nice! I will update or API to pass the variable. The hash is provided by code-server but I'm not aware of how do they generate it.
We should be able to catch potential hash changes when we update the docker image.

**Comment by AdamZaczek** [comment]
@ShMcK Nice! I will update our API to pass the variable. The hash is provided by code-server but I'm not aware of how do they generate it.
We should be able to catch potential hash changes when we update the docker image.

**Comment by wygodaPaul** [comment]
Hi,
coderoad.coderoad v0.14.5 still does not work as intended with variable: 
CODEROAD_CONTENT_SECURITY_POLICY_EXEMPTIONS set to the hash. 
but now I got 'black' screen. 
![image](https://user-images.githubusercontent.com/33558885/134387033-afd5bc40-b9fd-4b11-9bea-bc6126580ffb.png)

**Comment by ShMcK** [comment]
Is the hash blanked out in the example above? I see the value set to `#`. Maybe it's not passing through properly?

Is there any way I could re-create the project locally to test the CSP exemption issue?

**Comment by moT01** [comment]
You can run one of the tutorials in CodeAlly with this code:

```
<html>
  <body style="margin: 0; padding: 0; overflow: hidden;">
    <iframe
      sandbox='allow-modals allow-forms allow-popups allow-scripts allow-same-origin'
      src='http://codeally.io/embed/?repoUrl=https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate'
      style="width: 100%; height: 100%;"
      title='Editor'
    />
  </body>
</html>
```
Put it in a `.html` file and open it in the browser. There may be some struggles getting it loaded up - it seems to get stuck on the last step before it's loaded. Refreshing the page will often get the loading process to finish for me.


There seems to be a bigger issue at the moment that probably needs to get resolved before you can load it up though. I keep seeing this:
![Screen Shot 2021-09-23 at 9 59 55 AM](https://user-images.githubusercontent.com/20648924/134532531-1addbc14-7428-4de7-86ec-368a0938f03c.png)
and the loading process doesn't get passed the first or second step. Seems like a recent issue - Any thoughts on that @AdamZaczek?

**Comment by AdamZaczek** [comment]
@moT01 Is this one issue still occurring? It has been fixed elsewhere already.

**Comment by wygodaPaul** [comment]
@ShMcK The issue with the black screen seems to be a problem on my end. Was testing it all on localhost. 
Probably nginx.
Still hash that @AdamZaczek provided me with was not working. The same Launching... screen is showing.

Sorry, but like I wrote earlier nginx probably denies any localhost tests. If you need to set some env's, you can send them to me, and I'll try to set them for you on production, or test it myself.

**Comment by AdamZaczek** [comment]
@ShMcK This doesn't seem to work.
We're adding the env variable you suggested to all our projects to make debugging this easier.

**Comment by moT01** [comment]
Just and FYI - I am able to get CodeRoad to load seemingly every time. I usually just have to close it and reopen a few times before it works.

**Comment by AdamZaczek** [comment]
We have a call regarding this and another issue with @ShMcK on Friday. I will keep you posted.

**Comment by AdamZaczek** [comment]
The initial error message is gone! Looks like we need an additional fix or two and we'll be good to go. My current errors: 
![image](https://user-images.githubusercontent.com/14284341/141764067-c7dd3470-558c-4cf2-8bc6-402e58b7e1c3.png)

**Comment by ShMcK** [comment]
@AdamZaczek do any of the errors result in broken functionality?

I believe the first error can be ignored

**Comment by AdamZaczek** [comment]
@ShMcK Yes, the loading is still stuck. To debug this, you can add a new playground project and add Coderoad there. Looks like a small part of your local fix didn't make it to the new release.
![image](https://user-images.githubusercontent.com/14284341/141973379-80becea9-13f0-4392-94f7-018faa021f4c.png)

**Comment by ShMcK** [comment]
I've been trying to debug this issue for a while now. It's hard to recreate:
- only reproducible in CodeAlly
- the extension does not provide any logs outside of the client
- I have to use the in-terminal editor to test code changes

As a result, I don't have any confidence on timelines for this one.

I'll try to keep this thread updated with what I discover:

- It's unlikely a CSP issue. Even with the most liberal of CSP rules, it fails at launch.

- It's unlikely a breaking code change. Git diffs between 0.14.2 (previously working) and 0.15.1 do not indicate any significant sources of the problem

- It may be an installation-related or build-related issue. When I install an older version of CodeRoad (0.14.4) on CodeAlly, it also does not work. There is a significant difference in the files between the CodeRoad preconfigured on CodeAlly and the installed version. I'll see if I can debug here further, but I may need some help on the CodeAlly side. I'm unclear on how we got 0.14.2 to work. @AdamZaczek.

**Comment by ShMcK** [comment]
I found the problem. 

I had a filter for events, to avoid events from other extensions: `event.origin.match(/^vscode-webview/)`

 But events from codeally have an origin of `https://codeally.io`.

**Comment by ShMcK** [comment]
![image](https://user-images.githubusercontent.com/4660659/142747597-eebfcb8f-06ad-4ca0-9008-834cda5b88ed.png)

Working with v0.15.2!

**Comment by AdamZaczek** [comment]
It looks like something broke regarding the content security policy @ShMcK . I can no longer open coderoad easily because of that.
It did open but after waiting for a while.

We can probably make it failsafe by following the example in https://code.visualstudio.com/api/extension-guides/webview#content-security-policy:
![image](https://user-images.githubusercontent.com/14284341/146422922-51956d7c-50f1-4de1-b457-3269a2326656.png)

**Comment by AdamZaczek** [comment]
Strangely enough, this started working. Maybe it was some issue with using an older coderoad.
