### ISSUE TITLE
CodeAlly not loading

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#27]
@moT01 Is this one issue still occurring? It has been fixed elsewhere already.

_Originally posted by @AdamZaczek in https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/26#issuecomment-926686685_

Moving this to a new issue

Yes, this is still occurring @AdamZaczek - it started just a few days ago, maybe Monday or so. It worked a few days before that. Another staff here saw that just now as well. Strangely, it loaded for him on the first try and then didn't after that. Seems to maybe not be picking up the repo URL? Here's my console:
<img width="1171" alt="Screen Shot 2021-09-24 at 10 24 40 AM" src="https://user-images.githubusercontent.com/20648924/134700639-6d1dadef-dcf7-4de0-b8ef-c2d4c908da4b.png">

Some null values in redux, as well:
![Screen Shot 2021-09-24 at 10 29 07 AM](https://user-images.githubusercontent.com/20648924/134701339-78415af5-c49a-4676-9e2d-c5b2f5fd99d1.png)

Not sure if any of those are necessary to load these up.

**Comment by AdamZaczek** [comment]
I see! We are working on passing the env parameters from Freecodecamp to CodeAlly and had to rework our URL mechanisms for that. We will handle this, thanks.

**Comment by AdamZaczek** [comment]
I see! We are working on passing the env parameters from Freecodecamp to CodeAlly and had to rework our URL mechanisms for that.
We will handle this asap.

**Comment by AdamZaczek** [comment]
We just deployed a large update of the flow needed to pass env variables.

Example link to try it out
https://codeally.io/embed/?repoUrl=https://github.com/codeallyio/hackathon-starter-codeally&envVariables=ENV_VARIABLE=VALUE,ANOTHER_VARIABLE=ANOTHER_VALUE

This will allow you to pass Freecodecamps variables directly to env variables in the container.

Working on those changes caused this issue. Let me know if it's working for you now!

**Comment by moT01** [comment]
This looks like it's working good 👍 Thanks 🎉

**Comment by Pbhacks** [comment]
It looks like the webpage at https://20770.vm-4r90428b041660123c34fa7bs.codeally.io/?r=64e8ae6517bfc8a71392204a20770&folder=/home/codeally/project&token= might be having issues, or it may have moved permanently to a new web address.

This issue is continuously coming pls resolve.
