### ISSUE TITLE
Can't load containers

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#28]
I haven't loaded up a tutorial in a week or two. Tried today - It doesn't seem to be working. I'm getting an error:

<img width="572" alt="Screen Shot 2021-10-22 at 10 56 05 AM" src="https://user-images.githubusercontent.com/20648924/138486064-5f238c67-22f8-44ac-a101-1ad333772190.png">

And the VM never loads up. I'm seeing this in my console:

![Screen Shot 2021-10-22 at 10 57 32 AM](https://user-images.githubusercontent.com/20648924/138486316-54669293-9565-499a-a8dc-9033dcc86cf8.png)

I cleared storage, tried on firefox and chrome - no luck. Couldn't get the 'Junior React Developer Challenge' loaded either. It seemed to load up the VM, but the VS Code interface never showed up:

![Screen Shot 2021-10-22 at 11 01 25 AM](https://user-images.githubusercontent.com/20648924/138486883-cd95fb70-ea6c-48d7-b14b-df61659f7d36.png)

It just hung there. It did say "Waiting for others..." at the top right. Not sure if someone was supposed to join or something and the interface would have showed up at that point. If you want any more info from me, like something from redux or something, let me know.

**Comment by AdamZaczek** [comment]
Our users are not reporting issues, maybe something broke because of trying to run both embeds and developer projects.

What email did you use?
Having a redux response pasted would also be great, thanks!

**Comment by AdamZaczek** [comment]
It should be fixed already @moT01 ! Let me know if you still have issues!

**Comment by moT01** [comment]
Thanks @AdamZaczek - Looks like it's working 🎉

I'm curious if that's something to do with my account, or from trying to open an embed link and developer project? I'm guessing that users will open one of my tutorials (embed), see that it's powered by CodeAlly, and then open one of the developer projects. I'll give it a try and see if that's causing any problems.

**Comment by AdamZaczek** [comment]
We had an old mechanism for handling storage for embeds and it didn't work well when switching between embeds and normal projects. Thanks!
