### ISSUE TITLE
Logging in via embed could use some fine tuning

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#29]
I cleared my storage and started up a tutorial to see what a first time user would see. Here's a gif:
![Oct-26-2021 18-33-14](https://user-images.githubusercontent.com/20648924/139089849-460743cb-43da-4686-a91e-da384e191571.gif)

- It opens in a new tab, it would be nice if it opened in the same tab
- It took me to CodeAlly after I logged in, it should go to freeCodeCamp (localhost when developing) - although I tried again today and it took me to localhost. So maybe this is fixed? or it was a one time thing or something - not sure what the difference was. The attempt today took me to `http://localhost:8000//?repoUrl=https://github.com/freeCodeCamp/learn-number-guessing-game&envVariables=undefined;undefined` after logging in - which put my at the homepage of my local fcc. I would like users to go to the page they came from, which would look something like `http://localhost:8000/learn/relational-databases/learn-relational-databases/number-guessing-game`

Not sure if this helps, but the login button takes me to `https://codeally.io/fromEmbed/login/?repoUrl=https://github.com/freeCodeCamp/learn-number-guessing-game&goBackTo=http://localhost:8000/&envVariables=undefined` 

The code I’m using looks like this:
```
<iframe
  className='codeally-frame'
  sandbox='allow-modals allow-forms allow-popups allow-scripts allow-same-origin'
  src={`https://codeally.io/embed/?repoUrl=${url}${envVariables}`}
  title='Editor'
/>
```
The `src` would translate to something like: `http://codeally.io/embed/?repoUrl=https://github.com/freeCodeCamp/learn-celestial-bodies-database&envVariables=CODEROAD_WEBHOOK_TOKEN=${webhookToken}`

I tried adding a `goBackTo` in there: `https://codeally.io/embed/?repoUrl=${url}${envVariables}&goBackTo=${goBackTo}` - it didn't seem to have any effect.

To reiterate and simplify the two problems:
- open in the same tab
- take users back to where they came from

Let me know if I can help 👍

**Comment by AdamZaczek** [comment]
There is a reason why it works like this.
OAuth prevents authentication inside iframes.
Because of this, we need to redirect to CodeAlly first.
We redirect to CodeAlly to log you in and we redirect users back after that.

What we can do is redirect to a /redirect page instead - and make it show a loader!

**Comment by moT01** [comment]
> OAuth prevents authentication inside iframes.

Yea, I thought there was a reason for it. Wonder if we can or should do it all the same tab though. Navigate the existing tab to CodeAlly, and redirect back to freeCodeCamp after a user is logged in. Not that big of a deal if a second tab opens, but I think one would be better. It would be nice to end up back on the page they started at though - then the container would (I think) start loading as soon as they end up back there.

> What we can do is redirect to a /redirect page instead - and make it show a loader!

Not sure if I understand what that would look like. I don't see anywhere in particular a loader is needed. Oh, you mean that flash of the CodeAlly homepage? I don't think that's a big deal. I suppose a loader might be a little better - but it's so quick users won't know what happened. I'll leave that up to you.

**Comment by AdamZaczek** [comment]
> Yea, I thought there was a reason for it. Wonder if we can or should do it all the same tab though. Navigate the existing tab to CodeAlly, and redirect back to freeCodeCamp after a user is logged in. Not that big of a deal if a second tab opens, but I think one would be better. It would be nice to end up back on the page they started at though - then the container would (I think) start loading as soon as they end up back there.

It should not be possible in the same tab because we work within two different domains.
Oauth forbids it.

What we're doing is working around the specification by logging users in within CodeAlly and redirecting after.
And this has to be done from CodeAlly as a top domain.

The redirect page will serve as a loader page, to add a smooth transition.

**Comment by moT01** [comment]
Wonder if there's a way to auto close that first tab when the new one opens.

**Comment by moT01** [comment]
This isn't an MVP issue - it works pretty good. But it would be nice to get the redirect to take users back to the page they came from after they're all logged in.

**Comment by moT01** [comment]
I'm going to close this. I think the process is quite smooth - we can create new issues if there's something specific we still want to improve.
