### ISSUE TITLE
Startup terminal commands don't run

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#31]
The [startup terminal commands](https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs/blob/main/codeAlly.json#L2) don't work. They were working at one point, then stopped, then the issue got fixed - and now they don't work again. This isn't an MVP issue - it's good enough for now.  I think, ideally, the container would load with no terminals open or one terminal open and the start up commands worked. I'm not sure how complex some of this is - it may not be easy. The UX isn't too bad how it is - I'm fine leaving it for now.

**Comment by AdamZaczek** [comment]
Note to anyone working on this:
Running tutorial projects is significantly faster now. Part of that is because we no longer add our own extension.
We can make this work in two ways:
1. By making a compact extension for tutorials.
2. By making a pull request to coderoad.

**Comment by moT01** [comment]
update: the terminal starts out hidden (I think) on the latest product, which is great. But you need to open a terminal, and manually shut it down before it's updated. For example, I change the bashrc to generate logs, those logs don't take effect unless a new terminal is opened. So you have to open the hidden one, trash it, and open a new one. Not a big deal, just an update.

**Comment by ShMcK** [comment]
@moT01 you can also run the command `source ~/.bashrc` which is the equivalent of closing and re-opening the terminal. 
https://devconnected.com/source-command-on-linux-explained/

**Comment by moT01** [comment]
Thanks for the tip @ShMcK. I've tried that before and I'm pretty sure it previously didn't work because the terminal was already open and that command ran in a sub process or whatever and not the open terminal. But, it may work now that the terminal is closed or hidden by default. I'll give it another try. 👍

**Comment by moT01** [comment]
Another test shows that the bashrc is working as intended. You don't need to close the terminal and start a new one. The terminal is closed by default, and when a user opens a new one, the bashrc is used. The first command just doesn't run the tests automatically because the bash_history file isn't created yet. So they run the first command, which creates the bash_history file - I have CodeRoad set to watch that file, but it doesn't recognize that file changed when it doesn't exist yet. I should be able fix this in the tutorials by creating that file in the startup commands - I'll give it a try. Just out of curiosity, is there any way to get CodeRoad to recognize that @ShMcK? Assuming that's what is happening.

**Comment by ShMcK** [comment]
Some observations:

The bash history exists on startup. But on startup, the commands are not logging to the bash history.
![image](https://user-images.githubusercontent.com/4660659/148701208-a7eb2b44-2ead-452f-bed9-66ba719fd179.png)

On reloading the terminal, it works as expected and shows it has been logging to the bash history the whole time. It passes on "echo hello git".
![image](https://user-images.githubusercontent.com/4660659/148701230-67cdeaec-5e01-428a-942c-59a6fa5eddab.png)


If the first command you run is "source ../.bashrc" it works as expected. It passes on "echo hello git" from the start.
![image](https://user-images.githubusercontent.com/4660659/148701365-8e5e1f8f-3dbe-4c61-86cc-e57a45c38b14.png)

A possible fix: add the following to the bottom of the `.bash_profile` file. It should automatically source the .bashrc.

```
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
```

**Comment by moT01** [comment]
I added the bash_history before the tutorial starts, so the command works right away.
