### ISSUE TITLE
Tutorials should perserve the progress across container sessions.

### ISSUE THREAD

**Issue by AdamZaczek** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#32]
**Describe the bug**
Progress in the tutorial is lost if the user stops the session and comes back again later on.
The progress is stored in localStorage and should be stored in a file instead.

**To Reproduce**
1. Open a tutorial
2. Make some progress
3. Open another tutorial
4. Go back to the first tutorial
5. See that the progress is lost

**Expected behavior**
Progress should be persisted

**Additional context**
We need to know where is the progress stored and read so we can apply the fix @ShMcK. Thanks in advance!

**Comment by ShMcK** [comment]
My initial thoughts:

- [x] add an env variable: `CODEROAD_SESSION_FILE_PATH` (string) as a path to the file to write/read from
- [x] if the variable exists AND a localStorage session is not found, read the session from the file if its found
- [x] if the variable exists, write session progress to the file as well as local storage

Considerations:
- We should not write to the workplace directory or it will mess with Git
- We may hit permissions errors in VSCode or Node when trying to write to a file outside of the workplace
- We may hit file system permission errors if the process does not have write or read access
- The file should be read as text and validated as it could be a vector for attack

**Comment by AdamZaczek** [comment]
I agree with your implementation thoughts,

Regarding considerations:
_We should not write to the workplace directory or it will mess with Git_
Agreed

_We may hit permissions errors in VSCode or Node when trying to write to a file outside of the workplace_
We already tested this in another case and it works as long as the final file path is not protected. It won't be once we pass
the proper CODEROAD_SESSION_FILE_PATH variable.

_We may hit file system permission errors if the process does not have to write or read access_
As above

_The file should be read as text and validated as it could be a vector for attack_
Good point!

Do you want to handle the Coderoad part of the task? We will provide you with the env variable.

**Comment by ShMcK** [comment]
I think I can handle the CodeRoad part, I have a basic implementation ready (see PR above). But I'll test it more and adjust.

**Comment by ShMcK** [comment]
Now published in CodeRoad v0.16 on open-vsx.

To make it work, add the following env var: `CODEROAD_SESSION_STORAGE_PATH` and pass in the path to the folder where session can be stored.

**Comment by AdamZaczek** [comment]
Awesome, I'm handling this today!

**Comment by AdamZaczek** [comment]
This feature probably causes https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/33 to happen. Needs investigation.

**Comment by AdamZaczek** [comment]
Just an update - this is already updated according to @ShMcK's suggestion from https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/33.

**Comment by AdamZaczek** [comment]
Just a heads up - this is already updated according to @ShMcK's suggestion from #33.

**Comment by AdamZaczek** [comment]
This is already working @moT01, thanks to Shawn pointing out a missing env variables issue when continuing an existing project.

Closing!
