### ISSUE TITLE
man pages are gone

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#35]
The `man` pages are gone. I use this command in many tutorials, e.g. `man echo`, quite frequently, to show users info about a command. So we need to add those back if possible. Screenshot:
![Screen Shot 2022-01-07 at 1 48 33 PM](https://user-images.githubusercontent.com/20648924/148650029-0b05c02e-46d2-4bc7-9d12-8efe54a9328c.png)

**Comment by AdamZaczek** [comment]
We're on it.

**Comment by AdamZaczek** [comment]
```bash
sudo unminimize
```
fixes the issue temporarily but takes some time. We're building a new docker image to have the man command enabled by default.

**Comment by AdamZaczek** [comment]
The man command is now available @moT01 
![image](https://user-images.githubusercontent.com/14284341/149322888-9bfebd97-b133-4939-b176-b8891eec11ca.png)
