### ISSUE TITLE
CodeRoad doesn't always load up

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#38]
Once in a while, I would see this when CodeRoad loaded:
<img width="387" alt="Screen Shot 2022-01-08 at 10 12 20 AM" src="https://user-images.githubusercontent.com/20648924/148651375-7c49454d-e32c-4549-8c60-72f4bc28c635.png">

And it just stayed blank. Had to close and reopen CodeRoad to get it working. It was fairly rare. I saw it once when initially loading a tutorial, and a couple times when trying to continue a tutorial. Probably made 10-15 tries at each (initial load and continue). For the most part, it was working great. I don't think this is a big issue, our users will have to deal with it for now I think. Making an issue anyway.

**Comment by ShMcK** [comment]
@moT01 If you see it again, can you capture and share the logs?

1. Open the terminal
2. Select "output"
3. Select "CodeRoad (Logs)" from the dropdown

**Comment by moT01** [comment]
coderoad v0.18.4
```
Failed to read from /home/codeally/.local/coderoad_tutorial.json: ENOENT: no such file or directory, open '/home/codeally/.local/coderoad_tutorial.json'
Failed to read or parse session file: ../../codeally/.local/coderoad_tutorial.json: No session file found
```

**Comment by ArielLeslie** [comment]
I'm having this problem consistently on Firefox (for Mac) with adblock off an no additional security.  I needed to close CodeRoad and run `CodeRoad:start` about 4 times before anything happened. During the attempts that didn't work, there was no coderoad log activity except the initial 
```bash
Workspace path: /home/codeally/.local/coderoad_tutorial.json
Reading file: /home/codeally/.local/coderoad_tutorial.json
Workspace path: /home/codeally/.local/coderoad_tutorial.json
coderoad v0.19.4
```

**Comment by moT01** [comment]
Bumping this. The problem persists - it's intermittent, sometimes it works, sometimes not. There may be two issues around this, not sure. CodeRoad sometimes doesn't load at all, and sometimes when it loads, the instruction stay blank like in the screen shot above.

It comes up on the forum quite a bit so it would be awesome if we could get this working consistently. I will try to dig in a little when I get a change and see if I can figure anything out.

**Comment by AdamZaczek** [comment]
We checked env vatiables. This are example ones I had when Coderoad did not start:
SHELL=/bin/bash
CODEALLY_INIT_COMMAND=exit
NVM_RC_VERSION=
COLORTERM=truecolor
TERM_PROGRAM_VERSION=1.57.1
CODEROAD_CONTENT_SECURITY_POLICY_EXEMPTIONS=sha256-O6s4HZqHNjMzg0UZUFHy0YEAlG05lWCXf0lBN+GmShk=
HOSTNAME=30473cc2c8a5
CODEALLY_PORT_4000=https://20412.vm-68a8g022ab6e066952c13ead7.silisky.com/
NODE_OPTIONS=--max-old-space-size=2048 
PWD=/home/codeally/project
CODEALLY_USER_ID=62c16d219a247953ce826f3f
CODEALLY_CURRENT_PROJECT_ID=62cf206e6cceb30d39fc7e30
VSCODE_GIT_ASKPASS_NODE=/usr/local/lib/node
HOME=/home/codeally
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
CODEROAD_WEBHOOK_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVG9rZW4iOiJaNDJKNm1zZmxtUFpGTktYVkZtTjNGbFZtT3ZoYUdmeEZVQ0x6S2w3ajM4aDJhZUlpTlRTRkNnN1hXVDdGSVNTIiwiaWF0IjoxNjU5NTQ0MDUyfQ.hd-aS5Cn-nr6T95Hw2-KNaCRiC4y-vHmaUzn6oVHgkI
CODEALLY_USER_TYPE=default
CODEALLY_ORIGINAL_PROJECT_ID=62cf206e6cceb30d39fc7e30
GIT_ASKPASS=/usr/local/lib/vscode/extensions/git/dist/askpass.sh
CODEALLY_USER_FULL_NAME=Adam Żaczek
CODEALLY_PORT_8080=https://20414.vm-68a8g022ab6e066952c13ead7.silisky.com/
NVM_DIR=/home/codeally/.nvm
CODEALLY_USER_PHOTO_URL=https://avatars.githubusercontent.com/u/14284341?v=4
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
ITEM_URL=https://open-vsx.org/vscode/item
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-61062badc5.sock
CODEALLY_PORT_8000=https://20413.vm-68a8g022ab6e066952c13ead7.silisky.com/
CODEALLY_IDLE_TIMEOUT=600000
CODEROAD_TUTORIAL_URL=https://raw.githubusercontent.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/main/tutorial.json
CODEROAD_SESSION_STORAGE_PATH=../../codeally/.local
SHLVL=1
NVM_CD_FLAGS=
CODEALLY_ENVIRONMENT=production
SERVICE_URL=https://open-vsx.org/vscode/gallery
CODEALLY_PORT_3000=https://20411.vm-68a8g022ab6e066952c13ead7.silisky.com/
CODEALLY_USER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmMxNmQyMTlhMjQ3OTUzY2U4MjZmM2YiLCJ0eXBlIjoiZGVmYXVsdCIsImlhdCI6MTY1ODgyNTkyM30.hP101jMBw4TfBYXykeHXWBju6dW-sSPaSXPypk67dRk
VSCODE_GIT_ASKPASS_MAIN=/usr/local/lib/vscode/extensions/git/dist/askpass-main.js
CODEROAD_DISABLE_RUN_ON_SAVE=true
PATH=/home/codeally/swift-5.3.3-RELEASE-ubuntu20.04/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
DEBIAN_FRONTEND=noninteractive
RBENV_ROOT=/home/codeally/.rbenv
TERM_PROGRAM=vscode
_=/usr/bin/printenv


Is something missing @ShMcK ?

The extension starts no problem if we start manually with 'coderoad start'.

**Comment by moT01** [comment]
Thanks for taking a look @AdamZaczek. I didn't know an extension could launch itself, I thought you might be telling it to launch or something - which is why I thought you might be able to help here. But I do think it's all on the CodeRoad side now - there might be some things I can do in the tutorial repos to help, as well. I will take a look.

**Comment by ShMcK** [comment]
The launching of CodeRoad is triggered by an "activation event". See the [activation event docs](https://code.visualstudio.com/api/references/activation-events).

Here's the code in the package.json of CodeRoad
```json
  "activationEvents": [
    "onCommand:coderoad.start",
    "workspaceContains:*/codeally.json",
    "workspaceContains:*/codeAlly.json", 
    "workspaceContains:*/.freeCodeCamp" 
  ]
  ```

 For a summary:
- `codeally.json` is intended to trigger a launch on startup and is added by CodeAlly.
- `.freeCodeCamp` is intended to exist when a project is being continued and is added by the tutorial creator @moT01 .
  
The `workspaceContains` fires when:
> This activation event is emitted and interested extensions will be activated whenever a folder is opened and the folder contains at least one file that matches a glob pattern.

When the workspace launches, it checks to see if the file exists. If it's not there at that time, the event doesn't fire. 

To test this, I opened a tutorial in CodeAlly and manually added a `codeally.json` file - it did not trigger the event to open CodeRoad. If I add the same file locally with the extension running, it opens CodeRoad. So there's some difference between VSCode locally and in CodeAlly (code-server). I looked to see if there were any breaking changes related to activation events in the [CodeServer changelog](https://github.com/coder/code-server/blob/main/CHANGELOG.md), but found nothing.

My guess is that there is probably some sort of race condition between:
1. the vscode workspace loading and checking `workspaceContains`
2. the specific folders/files being added in CodeAlly

If vscode loads, then the folders/files load, I might expect the extension **not** to open automatically.
If the folders/files load, then vscode, I might expect the extension to open on launch.

@AdamZaczek let me know if that makes sense?

**Comment by AdamZaczek** [comment]
It does. In fact, I just remembered about the activation events in the morning and wanted to write a similar analysis. Then I saw your message :D

This bug is sneaky. I was thinking about a fix.
How about, we modify the extension, to always auto launch in CodeAlly?

I remember discussing this briefly a while ago. We would have a "fork", with the activation events modified.
We can override the package.json manually, so there's no extra work on your side @ShMcK. We can add an automatic script, later. We would run it on our VMs.
This way, we would make sure, Coderoad always activates.

Thoughs @moT01 @ShMcK ?

**Comment by AdamZaczek** [comment]
Unless there's an bug for wildcard activationEvents, we can have this fixed even tomorrow, @ShMcK @moT01 .

**Comment by AdamZaczek** [comment]
Unless there's an bug for wildcard activationEvents, we can have this fixed even tomorrow, @ShMcK @moT01 .

**Comment by moT01** [comment]
I presume you added this @AdamZaczek? I'm seeing a lot more reliability when loading.

**Comment by AdamZaczek** [comment]
Actually, I did not!
@AceSpadeAble did make a ton of API improvements, and it's possible, that the race condition that was probably the cause, is happening a lot less as a result.

We need to implement a fix anyways just because we know that otherwise, the issue might pop up anytime.
I'm glad the issue is a lot less severe in the meantime!

**Comment by moT01** [comment]
So, the secondary issue here is that CodeRoad doesn't always load the course - even if it loads. Here's a few things I see...

On an initial load of a container (haven't started course):
```
Workspace path: /home/codeally/.local/coderoad_tutorial.json
Reading file: /home/codeally/.local/coderoad_tutorial.json
Workspace path: /home/codeally/.local/coderoad_tutorial.json
coderoad v0.19.4
Failed to read from /home/codeally/.local/coderoad_tutorial.json: ENOENT: no such file or directory, open '/home/codeally/.local/coderoad_tutorial.json'
Failed to read or parse session file: ../../codeally/.local/coderoad_tutorial.json: No session file found
```

Have started the course and completed a few steps - didn't manually open CodeRoad for some time, so the container files should have been loaded:
![Screen Shot 2022-08-09 at 5 09 17 PM](https://user-images.githubusercontent.com/20648924/183770935-e3741760-b9e5-43ec-a8b5-3df6144ce2e4.png)

What it looks like when it works:
```
Workspace path: /home/codeally/.local/coderoad_tutorial.json
Reading file: /home/codeally/.local/coderoad_tutorial.json
Workspace path: /home/codeally/.local/coderoad_tutorial.json
coderoad v0.19.4
Failed to read from /home/codeally/.local/coderoad_tutorial.json: ENOENT: no such file or directory, open '/home/codeally/.local/coderoad_tutorial.json'
Failed to read or parse session file: ../../codeally/.local/coderoad_tutorial.json: No session file found
STATE: "Setup.Startup"
ROUTE: "Setup.Startup": On level unknown, step unknown
EDITOR_STARTUP
Using tutorial url from env: https://raw.githubusercontent.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator/main/tutorial.json
Tutorial: Learn Advanced Bash by Building a Kitty Ipsum Translator (1.0.2)
START_TUTORIAL_FROM_URL
EDITOR_TUTORIAL_CONFIG
Workspace path: /home/codeally/.local/coderoad_tutorial.json
Writing file: /home/codeally/.local/coderoad_tutorial.json
Workspace path: /home/codeally/.local/coderoad_position.json
Writing file: /home/codeally/.local/coderoad_position.json
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
Calling command: node --version
Workspace path: /home/codeally/project/.git
Check file exists: /home/codeally/project/.git
Calling command: git --version
Calling command: git init
Calling command: git ls-remote --exit-code --heads https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator
Calling command: git ls-remote --exit-code --heads https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator v1.0.2
Calling command: git remote -v
Calling command: git remote add coderoad https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator && git fetch coderoad
Calling command: git log -n 1 --pretty=format:%s 3b80d683663e38e9b48731337afb01995645c4ab
Calling command: git log -g --grep='INIT'
Error: Command failed: git log -g --grep='INIT'
fatal: your current branch 'master' does not have any commits yet

Calling command: git cherry-pick -X theirs 3b80d683663e38e9b48731337afb01995645c4ab
Command: ./.freeCodeCamp/setup.sh
COMMAND_START
Calling command: ./.freeCodeCamp/setup.sh
Command output: 
COMMAND_SUCCESS
Command: ./.freeCodeCamp/reset.sh
COMMAND_START
Calling command: ./.freeCodeCamp/reset.sh
Command output: 
COMMAND_SUCCESS
Command: cd .freeCodeCamp && npm install
COMMAND_START
Calling command: cd .freeCodeCamp && npm install
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
Command failed: npm WARN freecodecamp@1.0.0 No description
npm WARN freecodecamp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


COMMAND_FAIL
TUTORIAL_CONFIGURED
STATE: "Setup.SetupNewTutorial"
ROUTE: "Setup.SetupNewTutorial": On level unknown, step unknown
STATE: "Setup.StartTutorial"
ROUTE: "Setup.StartTutorial": On level 10, step 10.1
EDITOR_LEVEL_ENTER
Workspace path: /home/codeally/.local/coderoad_position.json
Writing file: /home/codeally/.local/coderoad_position.json
EDITOR_STEP_ENTER
Workspace path: /home/codeally/.local/coderoad_position.json
Writing file: /home/codeally/.local/coderoad_position.json
STATE: "Tutorial.Level.Load"
ROUTE: "Tutorial.Level.Load": On level 10, step 10.1
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 10, step 10.1
Calling command: git log -n 1 --pretty=format:%s 83746738040bcadae38eb00236da273abb2e4e3a
Calling command: git log -g --grep='10.1'
Calling command: git cherry-pick -X theirs 83746738040bcadae38eb00236da273abb2e4e3a
------------------- RUN TEST -------------------
START_TEST
COMMAND: npm run programmatic-test --reporter=mocha-tap-reporter
Calling command: npm run programmatic-test --reporter=mocha-tap-reporter
STATE: "Tutorial.Level.TestRunning"
ROUTE: "Tutorial.Level.TestRunning": On level 10, step 10.1
---------------- TEST RESULTS -----------------
TEST_FAIL
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 10, step 10.1
```

That `STATE: "Setup.Startup"` on line 7 isn't running for some reason. It doesn't seem like a race at this point since I waited quite a while in that screen shot - and I checked that `coderoad_position.json` file existed before starting. Any ideas @ShMcK?

**Comment by AdamZaczek** [comment]
This is probably it! We'll check why the files are missing in some cases. Thanks, @moT01

**Comment by moT01** [comment]
But the file is there in the screen shot. That's me starting a tutorial I'm in the middle of - CodeRoad did not load itself, I waited a moment, checked for that file in the terminal (it was there), then manually started CodeRoad - and it didn't load the course. It just kind of hung there. For some reason, it's not running that startup function.

For a little more context, that file doesn't exist the first time a user starts a tutorial- then CodeRoad creates it once they get to the first step.

I will check if I can reproduce this outside of CodeAlly.

**Comment by ShMcK** [comment]
@moT01 if you can reproduce the problem outside of CodeAlly, please let me know.

@AdamZaczek I'm happy to change the package.json file if it helps, that may be simpler than injecting over over-writing the file - which perhaps might lead to another race condition. If the target activation files have changed, we can update the package.json to reflect that.

**Comment by AdamZaczek** [comment]
The issue is fixed for new projects @ShMcK @moT01  🚀 

We were digging into the possible issue for a little bit but it's hard to figure out a non-hacky solution so we used an activationEvents wildcard.

If you open a project you have not opened before, it will load up consistently.
![image](https://user-images.githubusercontent.com/14284341/185608532-cae42c7e-9d3c-459a-b28a-fa6b9947d75d.png)

**Comment by moT01** [comment]
Awesome @AdamZaczek 🎉 Nice work 👍 CodeRoad loads up automatically every time now.

The secondary issue persists here, though - the course sometimes still doesn't load. This will likely have to be fixed on the CodeRoad side.

**Comment by AdamZaczek** [comment]
My observation was that Coderoad loads the files correctly if it's opened later, for example from the command line.
Did you observe the same behavior @moT01?
If this is the case, waiting a moment if the files fail to load, might do it. I wish I had a more educated fix suggestion. 

@ShMcK What I would check, is if you can open the course files after a timeout if the first attempt fails and repeat up to 10 or so times.

**Comment by moT01** [comment]
> My observation was that Coderoad loads the files correctly if it's opened later, for example from the command line.

I'm not quite sure what you mean by this. I'm not sure if it's related to when you open it - although, it might be. Sometimes it works right away, and sometimes it doesn't work until you close and reopen it a number of times. So perhaps it's just waiting on something else to finish or be there. If you are continuing a tutorial, the files will already be there, so CodeRoad would just need to run the startup function or something.

In [my post above](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/38#issuecomment-1209948624), I mention the difference between it working and not. When it doesn't work, it stops after the first four logs in that screen shot or six logs in the text above the screen show. When it does work, it runs the next command, `STATE: "Setup.Startup"` - so we maybe just need to force that to run or something. Maybe keep trying to run it if it hasn't been run yet.

**Comment by moT01** [comment]
I am going to close this for now. It's been loading up the course nicely every time for me for a while. If similar problems pop back up, we can revisit.
