### ISSUE TITLE
Remove firefox browser warning?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#40]
When I open up a container with firefox, I get a warning that says "Your browser might not provide the best CodeAlly.io experience..."
![Screen Shot 2022-01-08 at 10 58 52 AM](https://user-images.githubusercontent.com/20648924/148652861-bf9d7e58-0a94-40ea-8ebe-c6222005358b.png)

This isn't a problem, I just wanted to point out that I primarily use firefox, but have used chrome quite a bit with CodeAlly as well. I've never noticed any problems with firefox or differences between the two. Wondering if firefox could be added to that list of recommended browsers and not show the pop up for it. Just sharing, no need to do it. We can close this whenever.

**Comment by AdamZaczek** [comment]
We had a ton of issues with how Firefox handles WebSockets but it seems like they have been fixed. I will remove the warning and we will monitor possible errors.
