### ISSUE TITLE
Bottom of terminal is cut off

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#41]
Pretty minor, but the bottom of the terminal is a little cut off...
![Screen Shot 2022-01-09 at 1 57 14 PM](https://user-images.githubusercontent.com/20648924/148698482-d983c1c1-5378-451c-8cc7-bbad3abe59c0.png)

Pretty sure it didn't used to do that. Any characters that hang below the baseline or whatever get a little cut off. The `g` from `git status` in the image, for example. It doesn't need to be fixed, just bringing it up.

I guess it could be from one of the VSCode settings I add - I don't think it is, though.

**Comment by AdamZaczek** [comment]
Good catch. I was working on making it easier to code on mobile devices. I missed the terminal problem.

Side note: We will try to make the mobile experience significantly better by closing the additional empty editor window.

**Comment by AdamZaczek** [comment]
Is this still the case for you? And did it occur on mobile?

I've been debugging this and turns out, some mobile browsers, like Samsung Galaxy 9+'s, have responsive imperfections.
For example, the bottom bar disappears on some mobile devices. It's super inconsistent and I think, we should leave it as is for now.

I was not able to see any issues on PCs. If you have some, a screenshot with more area will help as the one attached looks ok at first glance.

**Comment by moT01** [comment]
Yea, It's fine for now @AdamZaczek. I'll get you another screen shot next time I load it up.

**Comment by moT01** [comment]
![Screen Shot 2022-01-10 at 12 34 50 PM](https://user-images.githubusercontent.com/20648924/148820189-ac6f239a-9c0f-4101-8052-588a7a470f25.png)

It's very usable, but would be nice to see the whole characters. One specific character that's rough, is the underscore (`_`). I use it in the SQL tutorials frequently for database and table names, etc. You can just barely see the top of it. 

Image is on firefox, but I'm pretty sure it happens on chrome too. I'll check if/when I load something up on that.

**Comment by AdamZaczek** [comment]
> ![Screen Shot 2022-01-10 at 12 34 50 PM](https://user-images.githubusercontent.com/20648924/148820189-ac6f239a-9c0f-4101-8052-588a7a470f25.png)
> 
> It's very usable, but would be nice to see the whole characters. One specific character that's rough, is the underscore (`_`). I use it in the SQL tutorials frequently for database and table names, etc. You can just barely see the top of it.
> 
> Image is on firefox, but I'm pretty sure it happens on chrome too. I'll check if/when I load something up on that.

Nice, that's exactly the behavior we discovered on some mobile devices. This means we can test some possible fixes.

**Comment by AdamZaczek** [comment]
I made a hopefully temporary but probably working fix. You can now scroll to the bottom but the terminal and bottom panels are visible regardless of the device. The downside is that we have this ugly white space on some devices.
![image](https://user-images.githubusercontent.com/14284341/148836719-e25b3bb5-d35c-464c-bada-1bca39105729.png)

Let me know if you still see the issue!
