### ISSUE TITLE
iframe shifts left leaving a blank space

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#44]
Once in a while, the whole iframe shifts to the left, leaving a white space on the right...
![Screen Shot 2022-03-26 at 8 27 01 AM](https://user-images.githubusercontent.com/20648924/160241806-7756e2da-bed7-4250-ada4-682ed8eb3ada.png)

I think it may only happen when I have the preview button collapsed, but I'm not sure. I haven't seen it happen when it's expanded, but I've only seen it twice. I dug into the dev tools a little, it fixed itself when I un selected the transform for that button...
![Screen Shot 2022-03-26 at 8 32 34 AM](https://user-images.githubusercontent.com/20648924/160241903-74d48e54-431f-453b-9ea4-d47de3bcedef.png)

Not sure exactly what's causing it, but it seems to be something around that button. Pretty minor.

**Comment by AdamZaczek** [comment]
Woah, crazy. We'll take a look.

**Comment by moT01** [comment]
I noticed there seems to be conflicting hotkeys. CodeRoad uses `ctrl+enter` to run tests or move to a new lesson. When I have the preview tab focused, it opens and closes the preview tab. I don't think the conflicting hotkeys is a problem - it may have something to do with the iframe shifting though.

**Comment by moT01** [comment]
I haven't seen this in a while. I am going to close it for now. If the problem comes back, we can revisit.
