### ISSUE TITLE
Containers get a little buggy or something

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#45]
A number of reports came in about problems with a tutorial. [Here's the first](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231/34). In that image, the `.freeCodeCamp` and `.vscode` folders are empty, there's supposed to be a bunch of files in there - they get loaded by CodeRoad when the tutorial starts. So the files were there when that user started the course cause they went through a number of steps - then maybe they paused and when they came back, they were gone - not sure. I had this happen to one of my containers, same thing - files missing. I did a `git status` and got some kind of memory error I think. Unfortunately, I ended up deleting the container after attempting to find a way to get those users back on track without having to do that.

More reports:
[Same thread, a couple posts after the first link](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231/39)
[Same thread, right after that](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231/40)
[reddit user](https://www.reddit.com/r/FreeCodeCamp/comments/tqa0rj/problem_regarding_the_relational_database/)

All these reports came in within a short time of each other, around last Sunday.

**Comment by moT01** [comment]
A [couple more instances](https://forum.freecodecamp.org/t/rdbm-course-stuck-at-mario-dbs-last-challenge/503211) the last few days.

**Comment by AdamZaczek** [comment]
It's good that we have timing for those. We had a bug where some of the containers remained open for too long and it could cause problems like this. This is likely to stop happening now. Let me know if users still experience this.

**Comment by moT01** [comment]
Looks like whatever you did worked @AdamZaczek 👍 Haven't seen any reports like this in a while.
