### ISSUE TITLE
Webpack deploys + caching old html in iframes = crash

### ISSUE THREAD

**Issue by AdamZaczek** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#46]
**Describe the bug**
Embedded CodeAlly is loaded with a cached version. Webpack generates new chunk names on each deployment.
Because of this, cached HTML might be pointing to non-existent chunk names after a deployment which causes a website crash.

This problem is occurring when someone with a previously loaded CodeAlly, visits a page again after deployment.

Potential fixes:
1. Making chunk names deterministic should be possible but might take a moment.

2. Adding a random query string to iframe src, like ?date=${new Date().getMinutes()} will fix the issue.

3. Possibly, if we can keep old chunks, it should work as well. This might take a moment too.

**To Reproduce**
Visit freecodecamp.org/learn/relational-database/ before the deployment.
Deploy the code.
Visit freecodecamp.org/learn/relational-database/ again.
The app should crash.

**Expected behavior**
A new CodeAlly version is loaded

**Screenshots**

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/14284341/163557115-0ab7ef14-63a8-4e3a-9548-54c74082e9fe.png">

**Additional context**
This caching issue is only present for iframes as we're not caching index.html.
Iframe hoverer does.
Adding a query param to src will be the fastest possible fix.

**Comment by AdamZaczek** [comment]
We're almost there!
We have a test environment [link]( https://teal-sunburst-97d62b.netlify.app/) with a different domain but it still does not replicate Freecodecamp's one perfectly.

Test environment does not cache CodeAlly at all anymore!
When visiting freecodecamp.org, the cache still applies for the first render. It means a recurring user has to visit and than refresh the page for the cache to get invalidated.
It's likely that adding a dynamic name attribute here: [link to iframe's code](https://github.com/freeCodeCamp/freeCodeCamp/blob/4b1a5240375ac3f32f422e0d56a80f7c44b878ca/client/src/templates/Challenges/codeally/show.tsx#L238) will remove the last required refresh.
I found the solution here https://stackoverflow.com/questions/2648053/preventing-iframe-caching-in-browser

@moT01 Let's add the following to the iframe's code:
```
name={`codeAlly{Date.now()}`}
```

**Comment by moT01** [comment]
I added the suggestion - it probably won't be live until next week. I believe that should close this issue - let me know if I missed something.

**Comment by AdamZaczek** [comment]
Awesome, ok
