### ISSUE TITLE
Many users are stuck on last step of loading the environment

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#47]
I am not having any issues, but there's been a number of reports recently from users who are stuck on the last step of loading their VM's. Here's [one with a screen shot](https://forum.freecodecamp.org/t/stuck-on-the-last-step-of-loading-remote-environment/512927)

More:
https://forum.freecodecamp.org/t/relational-database-stuck-on-loading-starting-virtual-server/512731
https://forum.freecodecamp.org/t/stucking-on-starting-virtual-server/512923
https://forum.freecodecamp.org/t/relational-databases-course/512930

We deployed the third party cookie fix on May 27th, so it could be on our end.

**Comment by AdamZaczek** [comment]
This is an issue on our end. We're fixing it.

**Comment by AdamZaczek** [comment]
Ok, should work now.

Note: There were issues 8+ hours ago and just now. We're almost done making an instant report mechanism so we can react in minutes if an unexpected issue occurs.

Let me know if you still see any issues!

**Comment by moT01** [comment]
Awesome, thanks for the quick response @AdamZaczek 🎉

**Comment by moT01** [comment]
User:
![Screen Shot 2022-05-30 at 2 21 21 PM](https://user-images.githubusercontent.com/20648924/171050119-c57898a5-11a0-418e-ace7-e95f8b5f4f5a.png)
