### ISSUE TITLE
Issue loading CodeRoad: "Could not register service workers"

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#49]
A few reports have come in with a specific error when trying to load CodeRoad: "Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure…"

[Post 1](https://forum.freecodecamp.org/t/coderoad-not-loading-in-window/515581/2)
[Post 2](https://forum.freecodecamp.org/t/webview-error-operation-is-insecure/520592/3)

My initial thought is that it's some browser settings that are blocking something - but I'm wondering if anyone has any idea of something it might be on one of our ends.

**Comment by AdamZaczek** [comment]
It's probably a Firefox bug.
I imagine this started occurring when we fixed some of the localStorage issues. It's likely that this issue awaited behind the ones we fixed.

**Comment by AdamZaczek** [comment]
PS I just checked the link here https://forum.freecodecamp.org/t/coderoad-not-loading-in-window/515581/4 and noticed that completed challenges don't transfer.
Do you know why that might be the case @ShMcK ?
Could it be a lack of some env variable?
