### ISSUE TITLE
CodeAlly issue

### ISSUE THREAD

**Issue by Samrat223** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#51]
Multiple users and freeCodeCamp Team have been unable to start any of the Relational Database projects.

CodeAlly appears to get stuck at the Starting virtual server step. Refreshing does not resolve the issue.

Personally, I only tried 2 projects, and only waited ~30min for one, and ~10 min for the other.

![image](https://user-images.githubusercontent.com/79866966/184553216-16ddfaf7-c057-41a8-b6db-ded44ce077da.png)

To Reproduce

Go to https://www.freecodecamp.org/learn/relational-database
Choose any project
Start the project
Click _Run in CodeAlly
See VM get stuck
Expected behavior
The VSCode environment should load after a reasonable amount of time.

Screenshots

Desktop (please complete the following information):

OS: Windows 11
Browser: Chrome
Version: 104.0.5112.81
Additional context

The VMs were fresh (no other instances running), and the projects had never been started before.

**Comment by AdamZaczek** [comment]
Thank you for reporting @Samrat223 ! We're investigating this

**Comment by AdamZaczek** [comment]
The issue should be fixed, thanks to your report @Samrat223 . Let me know if it works for you!

**Comment by moT01** [comment]
This should be fixed @Samrat223, want to give it another try? I am going to close this. Let us know if you are still having issues and we can reopen it. Thanks and happy coding 🎉 

FYI - it shouldn't take more than a minute or so to load the container. If it takes any longer, it likely won't work and you should let us know here or on the forum. I updated the forum post to mention this so people hopefully don't spend that amount of time waiting.
