### ISSUE TITLE
VS Code Editor not correctly loading ([vscode] failed to initialize VS Code)

### ISSUE THREAD

**Issue by pgrigorakis** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#53]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17252974/189872796-20644b71-8135-4bbb-8677-31d5fae3f4e8.png)

![image](https://user-images.githubusercontent.com/17252974/189873161-ef7d53ea-a57d-4f7b-9f07-1429c1f36f14.png)

**To Reproduce**
1 Go to https://www.freecodecamp.org/learn/relational-database
2 Choose any project
3 Start the project
4 Click _Run in CodeAlly
5 Notice VS Code not loading

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 105.0.5195.102 & Edge 105.0.1343.27

**Comment by pgrigorakis** [comment]
@AdamZaczek Hi Adam, just to narrow this down a bit, I checked all the relational database modules and every single one except the [Mario Database (postgres module)](https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database) is working fine. This is the only one where vscode is not loading. Hope this helps.

**Comment by AdamZaczek** [comment]
Thank you @bohemian83. We will handle this one!

**Comment by AdamZaczek** [comment]
Thank you @bohemian83. We will handle this one! This bug should not appear to new users or to your new projects, but it's good that you reported it so we can fix it for you too.

**Comment by AdamZaczek** [comment]
I think it's safe to close this one as the underlying problem has been fixed. If you still experience the issue, please let me know.
