### ISSUE TITLE
Unreadable Terminal - Font Spacing/Styling Issue

### ISSUE THREAD

**Issue by psiryan** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#54]
**Describe the bug**
Terminal font spacing is too narrow making the terminal unreadable.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/relational-database/
2. Select Mario Database from the course list
3. Click on 'Run with CodeAlly' button
4. When CodeRoad launches, open new terminal (I use Ctrl+` hotkey)
5. See issue

**Expected behavior**
Expecting to see a clear and readable terminal font that is properly spaced.

**Screenshots**
![image](https://user-images.githubusercontent.com/5029072/191502676-cb8ab1cb-ca16-4c91-84ca-6649dbf7a0d4.png)

**Desktop (please complete the following information):**
 - OS: OS: Arch Linux (x86_64 Linux 5.15.63-1-lts)
 - Browser: FireFox (104.0 64-bit)

**Additional context**
This happened multiple times for me during the Boiler Plate course; somehow it seemed to resolve itself after a few days, but now I see the issue again on the Mario Database course. Presumably this will/can/has happened for other people on other courses.

If the text is highlighted the issue goes away:
![image](https://user-images.githubusercontent.com/5029072/191505249-9f3f8df7-9bd0-44ca-92d7-277d74f6188a.png)

However it is not desirable to have to highlight my terminal IO just to be able to read it.

**Comment by ShaunSHamilton** [comment]
This is a common bug I have seen in applications that use [xterm](https://www.npmjs.com/package/xterm). As CodeAlly is running a flavour of VSCode, I assume that is the culprit.

I am not sure much can be done about this.

**Comment by AdamZaczek** [comment]
Thank you for reporting @psiryan. That's right @ShaunSHamilton. We don't control the xterm directly and styling issues happen occasionally. Source: https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+xterm.
We need to wait for the fixes on the xterm/vscode side.
