### ISSUE TITLE
unable to log in: bad verification code

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#62]
<details>
  <summary>Console Error</summary>

```json
[
    {
        "message": "Could not login. You must wait at least a day since creating a github account to use it in CodeAlly!",
        "locations": [
            {
                "line": 2,
                "column": 3
            }
        ],
        "path": [
            "githubAuth"
        ],
        "extensions": {
            "authResponse": {
                "size": 0,
                "timeout": 0
            },
            "auth": {
                "error": "bad_verification_code",
                "error_description": "The code passed is incorrect or expired.",
                "error_uri": "https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"
            },
            "code": "TOO_NEW_ACCOUNT",
            "exception": {
                "authResponse": {
                    "size": 0,
                    "timeout": 0
                },
                "auth": {
                    "error": "bad_verification_code",
                    "error_description": "The code passed is incorrect or expired.",
                    "error_uri": "https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"
                }
            }
        }
    }
]
````

</details>

I have had my GitHub account for many years. So, the error does not make sense.

The log in screen also just hangs at "redirecting":
<img width="414" alt="image" src="https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/assets/51722130/683b8ff6-00da-4ec3-b96a-5c8d0f64d94c">

**Reproduction**:
1) Go to https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate
2) Start course
3) Click CodeAlly "Login to start coding" button
4) Follow auth steps until error

**Comment by moT01** [comment]
I was unable to reproduce this after trying two different GH accounts.

**Comment by AdamZaczek** [comment]
Hi @ShaunSHamilton , we will check what might be wrong. Just to be sure, you were using your current account right?

**Comment by ShaunSHamilton** [comment]
@AdamZaczek Yes, this is the account I was using - I have no others.

**Comment by AdamZaczek** [comment]
Hi @ShaunSHamilton. We deployed fixes to the auth issues. Your account looks ok. Sometimes GitHub errors for one login, seemingly to ask users to re-authenticate and that's likely what has been happening for you. In that case, we show the login button with a message asking to re-authenticate.

Please let me know if your problem persists.

**Comment by ShaunSHamilton** [comment]
Thank you, Adam. However, now I get this error:

```json
[
    {
        "message": "Something went wrong when calling GitHub API. Please try again.",
        "locations": [
            {
                "line": 2,
                "column": 3
            }
        ],
        "path": [
            "githubAuth"
        ],
        "extensions": {
            "authResponse": {
                "size": 0,
                "timeout": 0
            },
            "auth": {
                "error": "bad_verification_code",
                "error_description": "The code passed is incorrect or expired.",
                "error_uri": "https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"
            },
            "code": "SOMETHING_WENT_WRONG",
            "exception": {
                "authResponse": {
                    "size": 0,
                    "timeout": 0
                },
                "auth": {
                    "error": "bad_verification_code",
                    "error_description": "The code passed is incorrect or expired.",
                    "error_uri": "https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"
                }
            }
        }
    }
]
```

And I get stuck here:
<img width="208" alt="image" src="https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/assets/51722130/e009a351-6a97-428f-8456-88fd4c268e09">

**Comment by AdamZaczek** [comment]
Thank you. What browser are you using?
Also, did you try logging in to CodeAlly directly first and than accessing the courses?

I wonder if your browser might be reloading an iframe unexpectedly, causing multiple auth requests to fire.
Would it be possible for you to record a session with a debugger open, [keeping networks logs](https://stackoverflow.com/questions/45133659/how-to-enable-preserve-log-in-network-tab-in-chrome-developer-tools-by-default) and a slow internet connection?

**Comment by ShaunSHamilton** [comment]
> What browser are you using?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

> Also, did you try logging in to CodeAlly directly first and than accessing the courses?

No. Should I do that first?

> Would it be possible for you to record a session with a debugger open, [keeping networks logs](https://stackoverflow.com/questions/45133659/how-to-enable-preserve-log-in-network-tab-in-chrome-developer-tools-by-default) and a slow internet connection?

Which debugger should I use? The only one I have used in a browser is the Redux Dev tools.

**Comment by Peter-gacc** [comment]
Shaun,
I have the same issue. Did you manage to sort out? I have the same issue when I tried to initiate the course. Any assistance would be really helpful.

**Comment by Peter-gacc** [comment]
Does logging in to CodeAlly directly first and then accessing the courses helps?

**Comment by ShaunSHamilton** [comment]
@Peter-gacc No, I am still unable to start a course.

Currently, the issue I am facing is:
1) Click on course
2) Click Log in
3) Log in with GitHub
4) Redirect to freeCodeCamp
5) Click on course
6) Repeat steps 2...

**Comment by Peter-gacc** [comment]
Yeah. That is the issue I am facing as well. When I click to the course, I am getting this

![Error](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/assets/32190878/a6961d76-a930-46cf-b106-c636391f1768)

**Comment by moT01** [comment]
Likely related: https://forum.freecodecamp.org/t/eta-for-fix-on-relation-database-curriculum-in-browser/650914

**Comment by djSublett** [comment]
I am currently seeing this issue as well
